name: Build and deploy ASP.Net Core app to Azure Web App - catastroapiack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish Web App
        run: dotnet publish SiteIntegraciones.csproj -c Release -o ${{ github.workspace }}/publish


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'catastroapiack'
          slot-name: 'Production'
          package: ${{ github.workspace }}/publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FD9A6AF8332442C1A3846545F496BAF8 }}
